var dinner = "Butter Chicken";
console.log("If dinner = `Butter Chicken`? I predict true");
console.log(dinner === "Butter Chicken");
console.log("If dinner = `Sabzi`? I predict false");
console.log(dinner === "Sabzi");
var breakfast = "Boiled Egg";
console.log("If breakfast = `Boiled Egg`? I predict true");
console.log(breakfast === "Boiled Egg");
console.log("If breakfast = `Half Fry Egg`? I predict false");
console.log(breakfast === "Half Fry Egg");
var lunch = "Pizza";
console.log("If lunch = `Pizza`? I predict true");
console.log(lunch === "Pizza");
console.log("If lunch = `Burger`? I predict false");
console.log(lunch === "Burger");
var snacks = "Chips";
console.log("If snacks = `Chips`? I predict true");
console.log(snacks === "Chips");
console.log("If snacks = `Chocolate`? I predict false");
console.log(snacks === "Chocolate");
var drinks = "Coffee";
console.log("If drinks = `Coffee`? I predict true");
console.log(drinks === "Coffee");
console.log("If drinks = `Tea`? I predict false");
console.log(drinks === "Tea");
